import "./globals.css";

import { ThemeProvider } from "../hooks/use-theme"
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { ModalProvider } from "@/provider/modal-provider";

export const metadata = {
  title: "Taste",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`antialiased light-blue`}
      >
        <ThemeProvider>
          {children}
        <ModalProvider/>
        </ThemeProvider>
        <ToastContainer
          position='bottom-center'
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme='dark'
        />
      </body>
    </html>
  );
}
